name: Build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        minecraft: [ 1.16.5, 1.17.1, 1.18.2, 1.19.4, 1.20.4 ]
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@main
      - name: Setup JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Setup ${{ matrix.minecraft }} ${{ matrix.loader }}
        run: ./gradlew setupLibrary -PbuildVersion="${{ matrix.minecraft }}"
      - name: Build ${{ matrix.minecraft }} ${{ matrix.loader }}
        run: ./gradlew build -PbuildVersion="${{ matrix.minecraft }}"
      - name: Capture release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/release
